name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display message
        run: echo "ho, I am GitHub action"
